### ISSUE TITLE
Add a fifth question

### ISSUE THREAD

**Issue by goodwid** [goodwid/the-fellowship#5]
Add a fifth question so there are no ties in race selection.

**Comment by YvonneHayes** [comment]
What does your dream home look like?
-  A cabin in the woods, surrounded by lush forrest and a tranquil little stream trickling by.
-  A sturdy house in the mountains built of stone. Close to natural resources and made of thick, secure walls! 
- A comfy little house in the country in walking distance to my friends and with pub around the corner!

**Comment by goodwid** [comment]
Question added!
